/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlataformaRouteImport } from './routes/plataforma'
import { Route as ShopIndexRouteImport } from './routes/$shop.index'
import { Route as ShopAdminRouteImport } from './routes/$shop.admin'
import { Route as ShopInstalarRouteImport } from './routes/$shop.instalar'
import { Route as ShopMeusAgendamentosRouteImport } from './routes/$shop.meus-agendamentos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlataformaRoute = PlataformaRouteImport.update({
  id: '/plataforma',
  path: '/plataforma',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/$shop/',
  path: '/$shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopAdminRoute = ShopAdminRouteImport.update({
  id: '/$shop/admin',
  path: '/$shop/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopInstalarRoute = ShopInstalarRouteImport.update({
  id: '/$shop/instalar',
  path: '/$shop/instalar',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopMeusAgendamentosRoute = ShopMeusAgendamentosRouteImport.update({
  id: '/$shop/meus-agendamentos',
  path: '/$shop/meus-agendamentos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/plataforma': typeof PlataformaRoute
  '/$shop/admin': typeof ShopAdminRoute
  '/$shop/instalar': typeof ShopInstalarRoute
  '/$shop/meus-agendamentos': typeof ShopMeusAgendamentosRoute
  '/$shop/': typeof ShopIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/plataforma': typeof PlataformaRoute
  '/$shop/admin': typeof ShopAdminRoute
  '/$shop/instalar': typeof ShopInstalarRoute
  '/$shop/meus-agendamentos': typeof ShopMeusAgendamentosRoute
  '/$shop': typeof ShopIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/plataforma': typeof PlataformaRoute
  '/$shop/admin': typeof ShopAdminRoute
  '/$shop/instalar': typeof ShopInstalarRoute
  '/$shop/meus-agendamentos': typeof ShopMeusAgendamentosRoute
  '/$shop/': typeof ShopIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/plataforma'
    | '/$shop/admin'
    | '/$shop/instalar'
    | '/$shop/meus-agendamentos'
    | '/$shop/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/plataforma'
    | '/$shop/admin'
    | '/$shop/instalar'
    | '/$shop/meus-agendamentos'
    | '/$shop'
  id:
    | '__root__'
    | '/'
    | '/plataforma'
    | '/$shop/admin'
    | '/$shop/instalar'
    | '/$shop/meus-agendamentos'
    | '/$shop/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlataformaRoute: typeof PlataformaRoute
  ShopAdminRoute: typeof ShopAdminRoute
  ShopInstalarRoute: typeof ShopInstalarRoute
  ShopMeusAgendamentosRoute: typeof ShopMeusAgendamentosRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plataforma': {
      id: '/plataforma'
      path: '/plataforma'
      fullPath: '/plataforma'
      preLoaderRoute: typeof PlataformaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$shop/': {
      id: '/$shop/'
      path: '/$shop'
      fullPath: '/$shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$shop/admin': {
      id: '/$shop/admin'
      path: '/$shop/admin'
      fullPath: '/$shop/admin'
      preLoaderRoute: typeof ShopAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$shop/instalar': {
      id: '/$shop/instalar'
      path: '/$shop/instalar'
      fullPath: '/$shop/instalar'
      preLoaderRoute: typeof ShopInstalarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$shop/meus-agendamentos': {
      id: '/$shop/meus-agendamentos'
      path: '/$shop/meus-agendamentos'
      fullPath: '/$shop/meus-agendamentos'
      preLoaderRoute: typeof ShopMeusAgendamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlataformaRoute: PlataformaRoute,
  ShopAdminRoute: ShopAdminRoute,
  ShopInstalarRoute: ShopInstalarRoute,
  ShopMeusAgendamentosRoute: ShopMeusAgendamentosRoute,
  ShopIndexRoute: ShopIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
